title: "Sharing Knowledge - Engenharia de Dados & ML"  
description: "Resenhas, estudos, artigos e minha jornada rumo a Machine Learning Engineering."
author: "Paulo Sergio"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

markdown: kramdown
highlighter: rouge

# Links sociais (opcional)
github_username: paulossergiojr
linkedin_username: paulossergio-pereira-junior

# Config de posts
permalink: /posts/:title/

# Excluir arquivos do build do GitHub Pages
exclude:
  - README.md
